services:   
  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    volumes:
      - ./server:/server
    ports:
      - 8000:8000
    env_file:
      - .env
    tty: true
    depends_on:
      - vector-server
      - sql-server

  vector-server:
    image: qdrant/qdrant
    container_name: qdrant
    volumes:
      - ./qdrant/qdrant_data:/qdrant/storage
      - ./qdrant/qdrant_snapshots/:/snapshots
    environment:
      QDRANT__STORAGE__SNAPSHOT_PATH: /snapshots
      QDRANT__TELEMETRY_DISABLED: 'true'
    ports:
      - 6333:6333

  sql-server:
    image: postgres
    container_name: mysql
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "jargone"
      POSTGRES_EXTENSIONS: "fuzzystrmatch"
    volumes:
      - psql_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d/

volumes:
  psql_data:
    driver: local
