from typing import Dict, Any

class MockLLMService:
    def generate_explanation(self, query: str, rag_results: Dict[str, Any]) -> Dict[str, Any]:
        """
        Mock LLM service that returns predefined explanations.
        In a real implementation, this would use an actual LLM to generate explanations.
        """
        # Mock response following the structure from the documentation
        return {
            "explanation": "This is a mock simple explanation of the highlighted text. "
                         "In a real implementation, this would be generated by an LLM "
                         "based on the RAG results and the original query.",
            "entities_found": [
                {
                    "entity": "Mock Technical Term",
                    "definition": "This is a mock simplified definition that would be "
                                "generated by an LLM based on the technical knowledge."
                }
            ]
        } 